# Generated by Django 5.2 on 2025-06-14 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Aktywność')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Znacznik czasu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Log Aktywności',
                'verbose_name_plural': 'Logi Aktywności',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('training_days', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('send_notification', models.BooleanField(default=False, help_text='Wysyłaj powiadomienia e-mail w dni treningowe')),
                ('trainer_notes', models.TextField(blank=True, null=True)),
                ('is_expert', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveIntegerField(default=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.exercise')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.trainingplan')),
            ],
            options={
                'unique_together': {('training_plan', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='exercises',
            field=models.ManyToManyField(related_name='plans', through='website.TrainingPlanExercise', to='website.exercise'),
        ),
        migrations.CreateModel(
            name='TrainingPlanCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='website.trainingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_completed'],
                'unique_together': {('training_plan', 'user', 'date_completed')},
            },
        ),
    ]
