# Generated by Django 5.2.3 on 2025-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='intensity',
            field=models.CharField(choices=[('low', 'Niska'), ('medium', 'Średnia'), ('high', 'Wysoka')], default='medium', max_length=6),
        ),
    ]
