# Generated by Django 4.2.20 on 2025-04-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_trainingplan_intensity"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="training_days",
            field=models.JSONField(default=list),
        ),
    ]
