# Generated by Django 4.2.20 on 2025-05-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_trainingplan_trainingdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
