# Generated by Django 4.2.20 on 2025-05-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_trainingplan_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="send_notification",
            field=models.BooleanField(
                default=False, help_text="Wysyłaj powiadomienia e-mail w dni treningowe"
            ),
        ),
    ]
