# Generated by Django 4.2.20 on 2025-05-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_trainingplan_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="trainer_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
