# Generated by Django 4.2.20 on 2025-05-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_trainingplan_send_notification"),
        ("website", "0005_trainingplan_trainer_notes"),
    ]

    operations = []
