# Generated by Django 4.2.20 on 2025-06-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_merge_20250530_1159"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="isExpert",
            field=models.BooleanField(default=False),
        ),
    ]
