# Generated by Django 4.2.20 on 2025-06-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_trainingplan_isexpert"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingplan",
            old_name="isExpert",
            new_name="is_expert",
        ),
    ]
